/**
 * WordPress Native Adapter — PHP template generation.
 *
 * Generates WordPress-compatible PHP templates with:
 * - get_header() / get_footer() template functions
 * - the_content() and custom fields support
 * - WordPress functions for images (wp_get_attachment_image), links, metadata
 * - Yoast/RankMath SEO meta compatibility
 * - Hero image, sections, code blocks, lists, tables, FAQ schema
 * - Edit overlay with vanilla JS
 *
 * Zero dependencies — uses only Node.js built-ins.
 */

const description = 'WordPress PHP template with get_header(), custom fields, Yoast/RankMath SEO';
const extensions = ['.php'];

/**
 * Generate a complete WordPress article template.
 *
 * @param {object} ir - Intermediate representation of article content
 * @param {string} ir.title - Article title
 * @param {string} [ir.description] - Article description
 * @param {string} [ir.content] - Raw HTML content body
 * @param {object} [ir.langConfig] - Language configuration
 * @param {object} [ir.tokens] - Design tokens
 * @param {object} [ir.meta] - Metadata (author, date, canonical, etc.)
 * @param {Array}  [ir.images] - Array of image objects {src, alt, width, height}
 * @param {Array}  [ir.sections] - Array of section objects {id, title, sidebarLabel, content, type}
 * @param {object} [ir.projectConfig] - Auto-detected project config
 * @param {Array}  [ir.faq] - FAQ items [{question, answer}]
 * @returns {{ files: Array<{path: string, content: string}> }}
 */
function generate(ir) {
  const {
    title = 'Untitled Article',
    description: articleDesc,
    content,
    langConfig = { direction: 'ltr', language: 'en' },
    tokens = {},
    meta = {},
    images = [],
    sections = [],
    projectConfig = {},
    faq = [],
  } = ir;

  const slug = slugify(title);
  const dir = langConfig.direction || 'ltr';
  const lang = langConfig.language || 'en';

  const files = [];

  // 1. Main PHP template
  const phpContent = generatePHPTemplate({
    title, articleDesc, content, langConfig, tokens,
    images, sections, dir, lang, meta, faq, slug,
  });
  files.push({ path: `template-article-${slug}.php`, content: phpContent });

  return { files };
}

// ── PHP Template ───────────────────────────────────────────────────

function generatePHPTemplate(opts) {
  const {
    title, articleDesc, content, langConfig, tokens,
    images, sections, dir, lang, meta, faq, slug,
  } = opts;

  const lines = [];

  // Template header comment (WordPress template identification)
  lines.push('<?php');
  lines.push('/**');
  lines.push(` * Template Name: Article - ${escapePHP(title)}`);
  lines.push(' * Template Post Type: post, page');
  lines.push(' *');
  lines.push(' * Auto-generated by ChainIQ Article Engine.');
  lines.push(' * Compatible with Yoast SEO and RankMath.');
  lines.push(' */');
  lines.push('');

  // Custom fields retrieval
  lines.push("$article_title = get_post_meta(get_the_ID(), '_article_title', true) ?: get_the_title();");
  lines.push(`$article_desc = get_post_meta(get_the_ID(), '_article_description', true) ?: ${phpString(articleDesc || title)};`);
  if (meta.author) {
    lines.push(`$article_author = get_post_meta(get_the_ID(), '_article_author', true) ?: ${phpString(meta.author)};`);
  } else {
    lines.push("$article_author = get_post_meta(get_the_ID(), '_article_author', true) ?: get_the_author();");
  }
  lines.push("$article_date = get_the_date('Y-m-d');");
  lines.push('');

  // get_header()
  lines.push('get_header();');
  lines.push('?>');
  lines.push('');

  // FAQ Schema (JSON-LD) — for Yoast/RankMath compatibility
  if (faq && faq.length > 0) {
    const schema = {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: faq.map(item => ({
        '@type': 'Question',
        name: item.question,
        acceptedAnswer: {
          '@type': 'Answer',
          text: item.answer,
        },
      })),
    };
    lines.push('<script type="application/ld+json">');
    lines.push(JSON.stringify(schema, null, 2));
    lines.push('</script>');
    lines.push('');
  }

  // Article container
  lines.push(`<article class="chainiq-article" dir="${escapeAttr(dir)}" lang="${escapeAttr(lang)}">`);

  // Header with hero image
  lines.push('  <header class="chainiq-article-header">');
  lines.push('    <h1 class="chainiq-article-title"><?php echo esc_html($article_title); ?></h1>');
  if (articleDesc) {
    lines.push('    <p class="chainiq-article-description"><?php echo esc_html($article_desc); ?></p>');
  }
  lines.push('    <div class="chainiq-article-meta">');
  lines.push('      <span class="chainiq-article-author"><?php echo esc_html($article_author); ?></span>');
  lines.push('      <time class="chainiq-article-date" datetime="<?php echo esc_attr($article_date); ?>"><?php echo esc_html(get_the_date()); ?></time>');
  lines.push('    </div>');

  // Hero image
  const heroImage = images && images.length > 0 ? images[0] : null;
  if (heroImage) {
    lines.push(buildHeroImagePHP(heroImage));
  } else {
    // Fallback to WordPress featured image
    lines.push('    <?php if (has_post_thumbnail()) : ?>');
    lines.push('      <div class="chainiq-hero-image">');
    lines.push("        <?php the_post_thumbnail('large', ['class' => 'chainiq-hero-img', 'loading' => 'eager']); ?>");
    lines.push('      </div>');
    lines.push('    <?php endif; ?>');
  }

  lines.push('  </header>');
  lines.push('');

  // Build TOC
  const tocItems = sections
    .filter(s => s.title)
    .map(s => ({ id: s.id || slugify(s.title), label: s.sidebarLabel || s.title }));
  const tocHTML = buildTOCHTML(tocItems);

  // Layout: main + sidebar
  lines.push('  <div class="chainiq-article-layout">');
  lines.push('    <main class="chainiq-article-main">');

  // Sections
  const sectionsHTML = buildSectionsPHP(sections, images, content);
  lines.push(sectionsHTML);

  lines.push('    </main>');
  lines.push('');
  lines.push('    <aside class="chainiq-article-sidebar">');
  if (tocHTML) lines.push(tocHTML);
  lines.push('    </aside>');
  lines.push('  </div>');
  lines.push('');

  // Edit overlay (vanilla JS)
  lines.push(generateEditOverlayPHP());

  lines.push('</article>');
  lines.push('');

  // Inline CSS
  lines.push('<style>');
  lines.push(generateInlineCSS(langConfig, tokens));
  lines.push('</style>');
  lines.push('');

  // get_footer()
  lines.push('<?php get_footer(); ?>');

  return lines.join('\n');
}

// ── Sections PHP Builder ───────────────────────────────────────────

function buildSectionsPHP(sections, images, fallbackContent) {
  if ((!sections || sections.length === 0) && fallbackContent) {
    return '      ' + fallbackContent;
  }
  if (!sections || sections.length === 0) {
    return '      <?php the_content(); ?>';
  }

  const parts = [];
  for (const section of sections) {
    const sectionId = section.id || slugify(section.title || '');
    const sectionContent = section.content || '';
    const sectionType = section.type || 'section';

    if (section.title) {
      const headingLevel = section.headingLevel || 2;
      const tag = `h${headingLevel}`;
      parts.push(`      <${tag} id="${sectionId}" class="chainiq-section-heading">${escapePHP(section.title)}</${tag}>`);
    }

    if (sectionType === 'code' || section.codeBlock) {
      parts.push(buildCodeBlockPHP(sectionContent, section.language));
    } else if (sectionType === 'list' && section.items) {
      parts.push(buildListPHP(section.items, section.ordered));
    } else if (sectionType === 'table' && section.rows) {
      parts.push(buildTablePHP(section.headers, section.rows));
    } else if (sectionType === 'image' && section.src) {
      parts.push(buildInlineImagePHP(section));
    } else if (sectionContent) {
      parts.push(`      <p>${escapePHP(sectionContent)}</p>`);
    }
  }

  return parts.join('\n\n');
}

// ── Hero Image ─────────────────────────────────────────────────────

function buildHeroImagePHP(image) {
  const src = image.src || image;
  const alt = image.alt || 'Hero image';
  return `    <div class="chainiq-hero-image">\n      <img\n        src="${escapeAttr(src)}"\n        alt="${escapeAttr(alt)}"\n        class="chainiq-hero-img"\n        loading="eager"\n      />\n    </div>`;
}

// ── Code Block ─────────────────────────────────────────────────────

function buildCodeBlockPHP(code, language) {
  const lang = language || '';
  const escapedCode = escapeHTML(code);
  return `      <pre class="chainiq-code-block">\n        <code${lang ? ` class="language-${lang}"` : ''}>${escapedCode}</code>\n      </pre>`;
}

// ── List ───────────────────────────────────────────────────────────

function buildListPHP(items, ordered) {
  const tag = ordered ? 'ol' : 'ul';
  const itemsHTML = items.map(item =>
    `        <li>${escapePHP(item)}</li>`
  ).join('\n');
  return `      <${tag} class="chainiq-list">\n${itemsHTML}\n      </${tag}>`;
}

// ── Table ──────────────────────────────────────────────────────────

function buildTablePHP(headers, rows) {
  let headerRow = '';
  if (headers && headers.length > 0) {
    const ths = headers.map(h => `            <th>${escapePHP(h)}</th>`).join('\n');
    headerRow = `        <thead>\n          <tr>\n${ths}\n          </tr>\n        </thead>`;
  }

  let bodyRows = '';
  if (rows && rows.length > 0) {
    const trs = rows.map(row => {
      const cells = (Array.isArray(row) ? row : [row]).map(
        cell => `            <td>${escapePHP(cell)}</td>`
      ).join('\n');
      return `          <tr>\n${cells}\n          </tr>`;
    }).join('\n');
    bodyRows = `        <tbody>\n${trs}\n        </tbody>`;
  }

  return `      <table class="chainiq-table">\n${headerRow}\n${bodyRows}\n      </table>`;
}

// ── Inline Image ───────────────────────────────────────────────────

function buildInlineImagePHP(section) {
  const src = section.src;
  const alt = section.alt || section.content || 'Article image';
  return `      <figure class="chainiq-figure">\n        <img src="${escapeAttr(src)}" alt="${escapeAttr(alt)}" class="chainiq-image" loading="lazy" />\n      </figure>`;
}

// ── Table of Contents ──────────────────────────────────────────────

function buildTOCHTML(items) {
  if (!items || items.length === 0) return '';

  const lis = items.map(item =>
    `          <li><a href="#${item.id}" class="chainiq-toc-link">${escapePHP(item.label)}</a></li>`
  ).join('\n');

  return `      <nav class="chainiq-toc" aria-label="Table of Contents">\n        <h3 class="chainiq-toc-heading">Contents</h3>\n        <ul class="chainiq-toc-list">\n${lis}\n        </ul>\n      </nav>`;
}

// ── Edit Overlay (Vanilla JS) ──────────────────────────────────────

function generateEditOverlayPHP() {
  return `  <!-- ChainIQ Edit Overlay -->
  <div id="chainiq-edit-root">
    <button id="chainiq-edit-toggle" class="chainiq-edit-button" aria-label="Edit article">
      Edit
    </button>
  </div>
  <script>
    (function() {
      var toggle = document.getElementById('chainiq-edit-toggle');
      var root = document.getElementById('chainiq-edit-root');
      var bridgeUrl = '<?php echo esc_js(get_option("chainiq_bridge_url", "http://127.0.0.1:19847")); ?>';

      toggle.addEventListener('click', function() {
        var panel = document.createElement('div');
        panel.className = 'chainiq-overlay-backdrop';
        panel.innerHTML =
          '<div class="chainiq-overlay-panel">' +
          '<h2>Edit Section</h2>' +
          '<p>Click on a section in the article to edit it. Changes are processed by the ChainIQ bridge server.</p>' +
          '<button class="chainiq-close-button">Close</button>' +
          '</div>';

        panel.querySelector('.chainiq-close-button').addEventListener('click', function() {
          panel.remove();
        });

        root.appendChild(panel);
      });
    })();
  </script>`;
}

// ── Inline CSS ─────────────────────────────────────────────────────

function generateInlineCSS(langConfig, tokens) {
  const dir = langConfig.direction || 'ltr';
  const isRTL = dir === 'rtl';
  const fontFamily = tokens.fontFamily
    || (langConfig.fonts ? langConfig.fonts.primary : 'system-ui, sans-serif');

  const lines = [];

  lines.push('  .chainiq-article {');
  lines.push('    max-width: 80rem;');
  lines.push('    margin-inline: auto;');
  lines.push('    padding: 3rem 1.5rem;');
  lines.push(`    font-family: ${fontFamily};`);
  lines.push(`    direction: ${dir};`);
  if (isRTL) {
    lines.push('    text-align: right;');
  }
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-article-header {');
  lines.push('    margin-bottom: 3rem;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-article-title {');
  lines.push('    font-size: 2.5rem;');
  lines.push('    font-weight: 700;');
  lines.push('    letter-spacing: -0.02em;');
  lines.push('    line-height: 1.2;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-article-description {');
  lines.push('    font-size: 1.125rem;');
  lines.push('    color: #6b7280;');
  lines.push('    margin-top: 0.5rem;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-article-meta {');
  lines.push('    display: flex;');
  lines.push('    gap: 1rem;');
  lines.push('    color: #6b7280;');
  lines.push('    font-size: 0.9rem;');
  lines.push('    margin-top: 0.75rem;');
  if (isRTL) {
    lines.push('    flex-direction: row-reverse;');
  }
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-hero-image {');
  lines.push('    margin-top: 2rem;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-hero-img {');
  lines.push('    width: 100%;');
  lines.push('    border-radius: 0.75rem;');
  lines.push('    object-fit: cover;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-article-layout {');
  lines.push('    display: grid;');
  lines.push('    grid-template-columns: 1fr 250px;');
  lines.push('    gap: 3rem;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-article-main {');
  lines.push('    font-size: 1.125rem;');
  lines.push('    line-height: 1.75;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-section-heading {');
  lines.push('    scroll-margin-top: 5rem;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-code-block {');
  lines.push('    border-radius: 0.5rem;');
  lines.push('    background: #f3f4f6;');
  lines.push('    padding: 1rem;');
  lines.push('    overflow-x: auto;');
  lines.push('    margin: 1.5rem 0;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-list {');
  lines.push('    padding-inline-start: 1.5rem;');
  lines.push('    margin: 1rem 0;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-table {');
  lines.push('    width: 100%;');
  lines.push('    border-collapse: collapse;');
  lines.push('    margin: 1.5rem 0;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-table th {');
  lines.push('    border: 1px solid #e5e7eb;');
  lines.push('    padding: 0.5rem 1rem;');
  lines.push('    text-align: start;');
  lines.push('    font-weight: 600;');
  lines.push('    background: #f9fafb;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-table td {');
  lines.push('    border: 1px solid #e5e7eb;');
  lines.push('    padding: 0.5rem 1rem;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-figure {');
  lines.push('    margin: 1.5rem 0;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-image {');
  lines.push('    max-width: 100%;');
  lines.push('    height: auto;');
  lines.push('    border-radius: 0.5rem;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-toc {');
  lines.push('    position: sticky;');
  lines.push('    top: 2rem;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-toc-heading {');
  lines.push('    font-size: 0.875rem;');
  lines.push('    font-weight: 600;');
  lines.push('    margin-bottom: 0.75rem;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-toc-list {');
  lines.push('    list-style: none;');
  lines.push('    padding: 0;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-toc-link {');
  lines.push('    display: block;');
  lines.push('    padding: 0.25rem 0;');
  lines.push('    font-size: 0.875rem;');
  lines.push('    color: inherit;');
  lines.push('    opacity: 0.7;');
  lines.push('    text-decoration: none;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-toc-link:hover {');
  lines.push('    opacity: 1;');
  lines.push('  }');
  lines.push('');

  // Edit overlay styles
  lines.push('  .chainiq-edit-button {');
  lines.push('    position: fixed;');
  lines.push('    bottom: 1.5rem;');
  lines.push('    right: 1.5rem;');
  lines.push('    z-index: 50;');
  lines.push('    background: #3b82f6;');
  lines.push('    color: white;');
  lines.push('    padding: 0.5rem 1rem;');
  lines.push('    border-radius: 0.5rem;');
  lines.push('    border: none;');
  lines.push('    cursor: pointer;');
  lines.push('    font-size: 0.875rem;');
  lines.push('    font-weight: 500;');
  lines.push('    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-overlay-backdrop {');
  lines.push('    position: fixed;');
  lines.push('    inset: 0;');
  lines.push('    z-index: 50;');
  lines.push('    background: rgba(0, 0, 0, 0.5);');
  lines.push('    display: flex;');
  lines.push('    align-items: center;');
  lines.push('    justify-content: center;');
  lines.push('    padding: 1rem;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-overlay-panel {');
  lines.push('    background: white;');
  lines.push('    border-radius: 0.75rem;');
  lines.push('    box-shadow: 0 25px 50px rgba(0, 0, 0, 0.25);');
  lines.push('    padding: 1.5rem;');
  lines.push('    max-width: 32rem;');
  lines.push('    width: 100%;');
  lines.push('  }');
  lines.push('');

  lines.push('  .chainiq-close-button {');
  lines.push('    padding: 0.5rem 1rem;');
  lines.push('    border: 1px solid #e5e7eb;');
  lines.push('    border-radius: 0.5rem;');
  lines.push('    background: transparent;');
  lines.push('    cursor: pointer;');
  lines.push('    font-size: 0.875rem;');
  lines.push('  }');
  lines.push('');

  lines.push('  @media (max-width: 1024px) {');
  lines.push('    .chainiq-article-layout {');
  lines.push('      grid-template-columns: 1fr;');
  lines.push('    }');
  lines.push('    .chainiq-article-sidebar {');
  lines.push('      display: none;');
  lines.push('    }');
  lines.push('  }');

  return lines.join('\n');
}

// ── Shared Utilities ───────────────────────────────────────────────

function slugify(str) {
  return String(str || '')
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80);
}

function escapeHTML(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function escapeAttr(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function escapePHP(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function phpString(str) {
  if (!str) return "''";
  return "'" + String(str).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
}

module.exports = { description, extensions, generate, slugify };
